# Generated by Django 5.0.1 on 2024-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOOD_APP', '0002_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_code', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
