# Generated by Django 5.0.1 on 2024-02-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOOD_APP', '0003_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
