# Generated by Django 5.0.1 on 2024-02-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FOOD_APP', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_id',
            new_name='item',
        ),
    ]
