# Generated by Django 5.0.1 on 2024-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOOD_APP', '0013_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
