# Generated by Django 5.0.1 on 2024-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOOD_APP', '0014_cart_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ordered'), (2, 'Pending'), (3, 'Delivered'), (4, 'Cancelled')], default=1),
        ),
    ]
