# Generated by Django 5.0.1 on 2024-03-12 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOOD_APP', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
