# Generated by Django 5.0.1 on 2024-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOOD_APP', '0017_notification_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
