from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login_page/', views.login_page, name='login_page'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('user_home/', views.userhome, name='user_home'),
    path('signup/', views.user_signup, name='user_signup'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('user_update', views.userupdate, name='user_update'),
    path('update_profile', views.updateprofile, name='update_profile'),
    path('Admin_Dashboard/', views.Admin_Dashboard, name='Admin_Dashboard'),
    path('items/', views.All_items, name='items'),
    path('add_item', views.add_item, name='add_item'),
    path('Added_Items', views.Added_Items, name='Added_Items'),
    path('edit_item/<int:id>/', views.edit_item, name='edit_item'),
    path('updated_item/<int:id>', views.updated_item, name='updated_item'),
    path('delete_item/<int:id>', views.delete_item, name='delete_item'),
    path('Menu/', views.Menu_items, name='menu'),
    path('Cart/<int:id>', views.Add_to_Cart, name='cart'),
    path('order/<int:id>', views.Order_item, name='order'),
    path('Add_Address/<int:id>', views.Add_Address, name='Add_Address'),
    path('Place_order', views.Place_order, name='Place_order'),
    path('All_Cart_items', views.All_Cart_items, name='All_Cart_items'),
    path('update_quantity_minus/',views.update_quantity_minus,name='update_quantity_minus'),
    path('update_quantity_plus/',views.update_quantity_plus, name='update_quantity_plus'),
    path('Update_address', views.Update_address, name='Update_address'),
    path('Delete_CartItem/<int:id>', views.Delete_CartItem, name='Delete_CartItem'),
    path('Order_all_item', views.Order_all_item, name='Order_all_item'),
    path('AddAddress', views.AddAddress, name='AddAddress'),
    path('PlaceCartOrder', views.PlaceCartOrder, name='PlaceCartOrder'),
    path('OrderDetails', views.OrderDetails, name='OrderDetails'),
    path('Order_ds', views.Order_ds, name='Order_ds'),
    path('Users_ds', views.Users_ds, name='Users_ds'),
    path('Accept_item/<int:id>', views.Accept_item, name='Accept_item'),
    path('Cancel_item/<int:id>', views.Cancel_item, name='Cancel_item'),
    path('Pending_item/<int:id>', views.Pending_item, name='Pending_item'),
    path('User_Notification', views.User_Notification, name='User_Notification'),
    path('Admin_Notification', views.Admin_Notification, name='Admin_Notification'),

]
